---
title: "data"
author: "Ben Best"
date: "January 2, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## R packages

See [rOpenSci - Packages](https://ropensci.org/packages/#data_publication). Here's a few particularly noteworthy ones:

* [ecoretriever](https://github.com/ropensci/ecoretriever): R interface to the [EcoData Retriever](http://ecodataretriever.org) with these [datasets](http://www.ecodataretriever.org/available-data.html), including [Gentry's    forest transects](http://www.davidzeleny.net/anadat-r/doku.php/en:data:gentry)

* [rdataone](https://github.com/DataONEorg/rdataone): R interface to [DataOne](https://search.dataone.org) with over 170K ecological datasets
* [dvn](https://github.com/ropensci/dvn): R interface to [Harvard Dataverse](https://dataverse.harvard.edu/dataverse.xhtml?alias=harvard&q=) with over 60K datasets
* [rfigshare](https://github.com/ropensci/rfigshare): R interface to [Figshare](https://figshare.com/browse)

* [rnoaa tutorial](https://ropensci.org/tutorials/rnoaa_tutorial.html): R interface to many NOAA data sources
* [rWBclimate tutorial](https://ropensci.org/tutorials/rwbclimate_tutorial.html): R interface for the World Bank climate data used in the [World Bank climate knowledge portal](https://github.com/ropensci/rnoaa)


## Specific Datasets

- [NEON Spatio-temporal Series Teaching Data Subsets | Figshare](https://figshare.com/articles/Spatio_temporal_Series_Teaching_Data_Subsets/2009586)

- [World beer consumption & scientific productivity.](https://figshare.com/articles/World_beer_consumption_scientific_productivity_/664162)

  - lake temps (Chris Lortie, Sapna)
    * [A global database of lake surface temperatures collected by in situ and satellite methods from 1985–2009 : Scientific Data](http://www.nature.com/articles/sdata20158)
    * [CRAN - Package laketemps](https://cran.r-project.org/web/packages/laketemps/index.html)
    * [USGS-R/laketemps](https://github.com/USGS-R/laketemps)
    * [GLTC - Global Lake Temperature Collaboration](http://www.laketemperature.org/)

  - ca alternative fuels (Cameron Gray)
    * [Alternative Fuels Data Center: Data Downloads](http://www.afdc.energy.gov/data_download/)
