---
title: "lec01_repro"
author: "Ben Best"
date: "January 2, 2016"
output: ioslides_presentation
---

# Introduction

## Environmental Informatics

- manipulating information to solve environmental problems

## Data Science

- "data science": Venn diagram of:

    1. math/stats
    
    1. specialty expertise, ie env science
    
    1. informatics
    
## Motivation Ex: OHI

- previously, one person curating all data & code, many scientists input.

- needed to open it up, elevate internal working group

- next, make available to whole world

- see this now for all R packages, for instance 

## Workflow

Install the necessary software (R, RStudio, Git) on your laptops. Then every week, you'll go through the following steps for each week's repository:

1. Fork

1. Clone

1. Commit

1. Push

1. Pull Request

[TODO: table with icons]

Idea is to **collaborate**! Will put this to the test with a student directory.

# Week 1: Reproducible Science Tools

## Reproducible Science Tools

# Setup

## Flagology

- Red flag = problem, help!

- Green flag = done, ready for next step.

## Feedback

- anonymous Google form

- Gitter forum

- issues

## Install Software

To have students complete assignments using forks (note: this setup means that **students will be able to see one another's work**):

## Fork Assignments

https://raw.githubusercontent.com/education/guide/master/docs/forks.md

1. To start, [**fork** the repository][forking].

### 1. Create the repositories

**[Create one repository][create-repo] per assignment**. Include any boilerplate files your students will need to get started.

If you'd prefer that your assignments or students' work isn't publicly visible, [request private repositories][private-repos] to use for your class. You will need one private repository per assignment.

### 2. Give students read-only access

**If your repositories are public, you can skip this step.**

If your course materials are in private repositories, students will need read-only access to them. Create a `students` team with "read access" and give that team access to all repositories that they will need. Next, add each student to the team, via [`add_to_team`][add-to-team-action] in our [teachers_pet][teachers-pet] tool, or [manually][help-add-to-team].

[Read more about access control][help-access-control].

### 3. Completing assignments

Your students then follow these steps for each assignment:

1. To start, [**fork** the repository][forking].
1. [**Clone**][ref-clone] the repository to your computer.
1. Modify the files and [**commit**][ref-commit] changes to complete your solution.
1. [**Push**][ref-push]/sync the changes up to GitHub.
1. [Create a **pull request**][pull-request] on the original repository to turn in the assignment.

You may consider making a context-specific copy of these steps in your syllabus or assignment description – grab [the markdown][raw].

### 4. Reviewing assignments

Once created, you can then do code review with line-by-line feedback directly within the pull request. If you allow your students to submit corrections, they can push fixes up to their forks, which will be reflected in the pull request.

Since you don't want any solutions in the original assignment repository, you should leave the pull request unmerged. When you're finished giving feedback, you can close the pull request and leave a :+1: (`:+1:`) in a final comment.

# Assignment 01: Students

## Describe Your Interests, use Markdown

- group project / phd thesis


- https://search.dataone.org
  - [Halpern B , Frazier M , Potapenko J , Casey K , Koenig K , Longo C , Lowndes J , Rockwood C , Selig E , Selkoe K , and Walbridge S. 2015. Cumulative human impacts: Supplementary data (doi:10.5063/F19Z92TW) Download](https://knb.ecoinformatics.org/#view/doi:10.5063/F19Z92TW)
  
  [Environment | Data](http://data.worldbank.org/topic/environment)


## Pick Core Datasets
* [Data Packaged Core Datasets](https://github.com/datasets)
* [Data Packages Listing - Frictionless Open Data](http://data.okfn.org/data)


<!-- Links -->
[create-repo]: https://help.github.com/articles/create-a-repo
[private-repos]: /guide/private_repos
[add-to-team-action]: https://github.com/education/teachers_pet/#giving-others-access
[teachers-pet]: https://github.com/education/teachers_pet
[help-add-to-team]: https://help.github.com/articles/adding-organization-members-to-a-team
[help-access-control]: https://help.github.com/articles/what-are-the-different-access-permissions#organization-accounts
[forking]: https://guides.github.com/activities/forking/
[ref-clone]: http://gitref.org/creating/#clone
[ref-commit]: http://gitref.org/basic/#commit
[ref-push]: http://gitref.org/remotes/#push
[pull-request]: https://help.github.com/articles/creating-a-pull-request
[raw]: https://raw.githubusercontent.com/education/guide/master/docs/forks.md